# Notification Service values
# CI updates ONLY the 'version' field

name: notification-service
version: fc6cf7a5f0cdaba445628d677dacb035f6083876  # ← CI overwrites this

image:
  repository: kyowanghwe99/new-notification-service
  pullPolicy: IfNotPresent

replicas: 1
port: 8083

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "768Mi"
    cpu: "500m"

# Env vars from common-config
commonConfigKeys:
  - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
    key: SPRING_KAFKA_BOOTSTRAP-SERVERS
  - name: LOKI_URL
    key: LOKI_URL
  - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
    key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT

# Env vars from service-specific ConfigMap
envFromConfigMap:
  - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL
    configMapName: notification-service-config
    configMapKey: SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL

# Service-specific ConfigMap
configMapData:
  SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL: "http://schema-registry.default.svc.cluster.local:8081"
