apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service-helm
  namespace: argocd
  labels:
    app.kubernetes.io/instance: microservices-apps
    finalizers: resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kyowanghwe/spring-boot-3-microservices-course.git
    targetRevision: deploy
    path: k8s/helm/microservice-chart
    helm:
      valueFiles:
        - values/notification-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
