# Frontend values
# CI updates ONLY the 'version' field

name: frontend
version: 7fa0fad0520ce3eab84c2f18ed20a28ff06951d3  # ← CI overwrites this

image:
  repository: kyowanghwe99/frontend
  pullPolicy: IfNotPresent

replicas: 1
port: 80

# Frontend doesn't need heavy resources
resources: null

# No config injection needed for frontend
commonConfigKeys: []
envFromConfigMap: []
